//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWT_Twitter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TweetHashtagConnection
    {
        public int ID { get; set; }
        public int Tweet { get; set; }
        public int Hashtag { get; set; }
    
        public virtual Hashtag Hashtag1 { get; set; }
        public virtual Tweet Tweet1 { get; set; }
    }
}
